# Generated by Django 4.2 on 2023-04-08 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_todo_description_todo_createdat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='todotasks',
            name='isCompleted',
            field=models.BooleanField(default=False),
        ),
    ]
